export const AFILIADOS_LIST_REQUEST = 'AFILIADOS_GET_REQUEST';
export const AFILIADOS_LIST_SUCCESS = 'AFILIADOS_GET_SUCCESS';
export const AFILIADOS_LIST_FAIL = 'AFILIADOS_GET_FAIL';

export const AFILIADOS_DETAILS_REQUEST = 'AFILIADOS_DETAILS_REQUEST';
export const AFILIADOS_DETAILS_SUCCESS = 'AFILIADOS_DETAILS_SUCCESS';
export const AFILIADOS_DETAILS_FAIL = 'AFILIADOS_DETAILS_FAIL';

export const AFILIADOS_DELETE_REQUEST = 'AFILIADOS_DELETE_REQUEST';
export const AFILIADOS_DELETE_SUCCESS = 'AFILIADOS_DELETE_SUCCESS';
export const AFILIADOS_DELETE_FAIL = 'AFILIADOS_DELETE_FAIL';

export const AFILIADOS_CREATE_REQUEST = 'AFILIADOS_CREATE_REQUEST';
export const AFILIADOS_CREATE_SUCCESS = 'AFILIADOS_CREATE_SUCCESS';
export const AFILIADOS_CREATE_FAIL = 'AFILIADOS_CREATE_FAIL';
export const AFILIADOS_CREATE_RESET = 'AFILIADOS_CREATE_RESET';

export const AFILIADOS_UPDATE_REQUEST = 'AFILIADOS_UPDATE_REQUEST';
export const AFILIADOS_UPDATE_SUCCESS = 'AFILIADOS_UPDATE_SUCCESS';
export const AFILIADOS_UPDATE_FAIL = 'AFILIADOS_UPDATE_FAIL';
export const AFILIADOS_UPDATE_RESET = 'AFILIADOS_UPDATE_RESET';
