export const AUTORIZACION_LIST_REQUEST = 'AUTORIZACION_LIST_REQUEST';
export const AUTORIZACION_LIST_SUCCESS = 'AUTORIZACION_LIST_SUCCESS';
export const AUTORIZACION_LIST_FAIL = 'AUTORIZACION_LIST_FAIL';

export const AUTORIZACION_DETAILS_REQUEST = 'AUTORIZACION_DETAILS_REQUEST';
export const AUTORIZACION_DETAILS_SUCCESS = 'AUTORIZACION_DETAILS_SUCCESS';
export const AUTORIZACION_DETAILS_FAIL = 'AUTORIZACION_DETAILS_FAIL';

export const AUTORIZACION_DELETE_REQUEST = 'AUTORIZACION_DELETE_REQUEST';
export const AUTORIZACION_DELETE_SUCCESS = 'AUTORIZACION_DELETE_SUCCESS';
export const AUTORIZACION_DELETE_FAIL = 'AUTORIZACION_DELETE_FAIL';

export const AUTORIZACION_CREATE_REQUEST = 'AUTORIZACION_CREATE_REQUEST';
export const AUTORIZACION_CREATE_SUCCESS = 'AUTORIZACION_CREATE_SUCCESS';
export const AUTORIZACION_CREATE_FAIL = 'AUTORIZACION_CREATE_FAIL';
export const AUTORIZACION_CREATE_RESET = 'AUTORIZACION_CREATE_RESET';

export const AUTORIZACION_UPDATE_REQUEST = 'AUTORIZACION_UPDATE_REQUEST';
export const AUTORIZACION_UPDATE_SUCCESS = 'AUTORIZACION_UPDATE_SUCCESS';
export const AUTORIZACION_UPDATE_FAIL = 'AUTORIZACION_UPDATE_FAIL';
export const AUTORIZACION_UPDATE_RESET = 'AUTORIZACION_UPDATE_RESET';
