export const INDIGENA_LIST_REQUEST = 'INDIGENA_LIST_REQUEST';
export const INDIGENA_LIST_SUCCESS = 'INDIGENA_LIST_SUCCESS';
export const INDIGENA_LIST_FAIL = 'INDIGENA_LIST_FAIL';

export const INDIGENA_DETAILS_REQUEST = 'INDIGENA_DETAILS_REQUEST';
export const INDIGENA_DETAILS_SUCCESS = 'INDIGENA_DETAILS_SUCCESS';
export const INDIGENA_DETAILS_FAIL = 'INDIGENA_DETAILS_FAIL';

export const INDIGENA_DELETE_REQUEST = 'INDIGENA_DELETE_REQUEST';
export const INDIGENA_DELETE_SUCCESS = 'INDIGENA_DELETE_SUCCESS';
export const INDIGENA_DELETE_FAIL = 'INDIGENA_DELETE_FAIL';

export const INDIGENA_CREATE_REQUEST = 'INDIGENA_CREATE_REQUEST';
export const INDIGENA_CREATE_SUCCESS = 'INDIGENA_CREATE_SUCCESS';
export const INDIGENA_CREATE_FAIL = 'INDIGENA_CREATE_FAIL';
export const INDIGENA_CREATE_RESET = 'INDIGENA_CREATE_RESET';

export const INDIGENA_UPDATE_REQUEST = 'INDIGENA_UPDATE_REQUEST';
export const INDIGENA_UPDATE_SUCCESS = 'INDIGENA_UPDATE_SUCCESS';
export const INDIGENA_UPDATE_FAIL = 'INDIGENA_UPDATE_FAIL';
export const INDIGENA_UPDATE_RESET = 'INDIGENA_UPDATE_RESET';
